# Generated by Django 2.2 on 2019-04-20 12:38

import authnz.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwt_secret', models.CharField(default=authnz.models.uuid_str, max_length=32)),
                ('phone_number', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('En', 'English'), ('Fr', 'French')], max_length=4)),
                ('currency', models.CharField(choices=[('D', 'Dollar'), ('E', 'Euro')], max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
